name: Create Release

on:
  push:
    branches: [ v5-lts ]
  workflow_dispatch:
  
env:
  GH_ACTIONS: 'true'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo files
        uses: actions/checkout@v2

      - name: Read checked out manifest.json
        id: read_manifest
        uses: MegaPiggy/json-reader-action@v1.0.0
        with:
          path: "BepInEx.Manifest.json"
          property: "version"

      - name: Check if version in manifest.json is already released
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: "v${{steps.read_manifest.outputs.version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cancel if version in manifest.json is already released
        if: ${{ !((steps.read_manifest.outputs.version != '0.0.0') && (steps.checkTag.outputs.exists == 'false')) }}
        uses: andymckay/cancel-action@0.2
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Restore tools
        run: dotnet tool restore

      - name: Build using Cake
        run: dotnet cake build.cake --target=Pack

      - name: Publish zip with version from manifest
        if: ${{ (steps.read_manifest.outputs.version != '0.0.0') && (steps.checkTag.outputs.exists == 'false') }}
        uses: softprops/action-gh-release@v1
        with:
          files: bin\dist\BepInEx_x86_*.zip
          tag_name: "v${{steps.read_manifest.outputs.version}}"